OFX Mapping fix to enable support to Money Pro
rubensflinco/nubank-ofx pull request #1
Opened 2016-07-11 19:22 UTC by addomafi

I've made some changes on the mapping of OFX file to be able to import transaction on application Money Pro for Mac OS X.

Another change regarding to the amount, where spends should be negative value.

2017-06-27 17:26 UTC, lucasprag commented
Nice! ping @gushonorato

2018-05-17 14:44 UTC, tonicospinelli requested changes
I'm not OFX specialist, but I think the lines that you added is only to have a "header", right?

2018-05-17 14:44 UTC, tonicospinelli commented on extrato-nubank.js
> +            return `
could you fix spaces here, pls?

2018-05-17 14:44 UTC, tonicospinelli commented on extrato-nubank.js
> +      <TRNAMT>${amount * -1}</TRNAMT>
👍

2020-12-03 00:10 UTC, marlonanjos commented
@addomafi I have forked this project to focus on compatibility with YNAB (where spends must be negative) and wanted to add Money Pro compatibility, are u still using it?

2020-12-03 15:49 UTC, gushonorato commented
@marlonanjos nice! Thanks! I don't use Money Pro anymore, but I can accept the changes for other people that use it. Can you fix the conflicts?

2020-12-03 19:21 UTC, addomafi commented
> @addomafi I have forked this project to focus on compatibility with YNAB (where spends must be negative) and wanted to add Money Pro compatibility, are u still using it?

Sorry i leave it... now I'm using the file provided from Nubank!

2024-07-24 03:51 UTC, closed without merging